general:
  label: General
  permalink: /general
  description: General tag description

commandline:
  label: Command Line
  permalink: /commandline
  description: Command Line tag description

kernel:
  label: Kernel
  permalink: /kernel
  description: Kernel tag description

virtualization:
  label: Virtualization
  permalink: /virtualization
  description: Virtualization tag description

containerization:
  label: Containerization
  permalink: /containerization
  description: Containerization tag description

sysadmin:
  label: System Administration
  permalink: /sysadmin
  description: System Administration tag description

networking:
  label: Networking
  permalink: /networking
  description: Networking tag description

devops:
  label: DevOps
  permalink: /devops
  description: DevOps tag description

automation:
  label: Automation
  permalink: /automation
  description: Automation tag description

security:
  label: Security
  permalink: /security
  description: Security tag description
